import { initializeApp } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js";
import { browserLocalPersistence,createUserWithEmailAndPassword,getAuth,onAuthStateChanged,sendPasswordResetEmail,setPersistence,signInWithEmailAndPassword,signOut } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-auth.js";
import { collection,deleteDoc,doc,initializeFirestore,onSnapshot,orderBy,persistentLocalCache,persistentMultipleTabManager,query,serverTimestamp,setDoc } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js";
import { firebaseConfig } from "./firebase-config.js";

const configurationView=document.querySelector('#configuration-view'),authView=document.querySelector('#auth-view'),appView=document.querySelector('#app-view'),authForm=document.querySelector('#auth-form'),emailInput=document.querySelector('#email'),passwordInput=document.querySelector('#password'),createAccountButton=document.querySelector('#create-account'),resetPasswordButton=document.querySelector('#reset-password'),authMessage=document.querySelector('#auth-message'),signOutButton=document.querySelector('#sign-out'),userEmail=document.querySelector('#user-email'),syncStatus=document.querySelector('#sync-status'),syncText=document.querySelector('#sync-text'),sourceText=document.querySelector('#source-text');
let auth,db,activeUser=null,unsubscribeWeights=null,latestSnapshotFromCache=true,hasPendingWrites=false;
const configured=()=>Object.values(firebaseConfig).every(v=>typeof v==='string'&&v.length>0&&!v.includes('PASTE_'));
const msg=(el,text,error=false)=>{el.textContent=text;el.classList.toggle('error',error)};
function friendly(e){const m={'auth/email-already-in-use':'An account already exists for this email.','auth/invalid-credential':'The email or password is incorrect.','auth/invalid-email':'Enter a valid email address.','auth/weak-password':'Use a password with at least six characters.','auth/network-request-failed':'No network connection. Existing signed-in sessions can still use cached data.','permission-denied':'Firestore denied access. Check the published security rules.'};return m[e?.code]??e?.message??'Something went wrong.'}
const weights=userId=>collection(db,'apps','weight-tracker','users',userId,'weights');
function networkStatus(){if(!navigator.onLine){syncStatus.className='sync-status offline';syncText.textContent=hasPendingWrites?'Offline · changes saved locally':'Offline · using local cache';sourceText.textContent='Will sync later'}else if(hasPendingWrites){syncStatus.className='sync-status';syncText.textContent='Synchronizing…';sourceText.textContent='Local changes pending'}else if(latestSnapshotFromCache){syncStatus.className='sync-status';syncText.textContent='Connected';sourceText.textContent='Checking cloud…'}else{syncStatus.className='sync-status synced';syncText.textContent='Synced';sourceText.textContent='Firebase up to date'}}
function today(){const n=new Date(),l=new Date(n.getTime()-n.getTimezoneOffset()*60000);return l.toISOString().slice(0,10)}
function formatDate(s){return new Intl.DateTimeFormat(undefined,{year:'numeric',month:'short',day:'numeric'}).format(new Date(`${s}T00:00:00`))}
function busy(v){authForm.querySelectorAll('button,input').forEach(x=>x.disabled=v)}
authForm.addEventListener('submit',async e=>{e.preventDefault();msg(authMessage,'');busy(true);try{await signInWithEmailAndPassword(auth,emailInput.value.trim(),passwordInput.value)}catch(err){msg(authMessage,friendly(err),true)}finally{busy(false)}});
createAccountButton.addEventListener('click',async()=>{msg(authMessage,'');busy(true);try{await createUserWithEmailAndPassword(auth,emailInput.value.trim(),passwordInput.value)}catch(err){msg(authMessage,friendly(err),true)}finally{busy(false)}});
resetPasswordButton.addEventListener('click',async()=>{const email=emailInput.value.trim();if(!email){msg(authMessage,'Enter your email first.',true);return}busy(true);try{await sendPasswordResetEmail(auth,email);msg(authMessage,'Password reset email sent.')}catch(err){msg(authMessage,friendly(err),true)}finally{busy(false)}});
function signedOut(){activeUser=null;unsubscribeWeights?.();unsubscribeWeights=null;authView.hidden=false;appView.hidden=true;passwordInput.value=''}
function signedIn(user){activeUser=user;authView.hidden=true;appView.hidden=false;userEmail.textContent=user.email??user.uid;subscribeToWeights(user.uid)}
function serviceWorker(){if(!('serviceWorker'in navigator))return;let pending=null,reloading=false;const banner=document.querySelector('#update-banner'),button=document.querySelector('#update-button');const show=w=>{pending=w;banner.hidden=false};window.addEventListener('load',async()=>{try{const reg=await navigator.serviceWorker.register('./service-worker.js',{updateViaCache:'none'});if(reg.waiting&&navigator.serviceWorker.controller)show(reg.waiting);reg.addEventListener('updatefound',()=>{const w=reg.installing;if(!w)return;w.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)show(w)})});reg.update().catch(console.error)}catch(e){console.error(e)}});button.addEventListener('click',()=>pending?.postMessage({type:'SKIP_WAITING'}));navigator.serviceWorker.addEventListener('controllerchange',()=>{if(reloading)return;reloading=true;location.reload()})}
async function init(){if(!configured()){configurationView.hidden=false;return}try{const app=initializeApp(firebaseConfig);db=initializeFirestore(app,{localCache:persistentLocalCache({tabManager:persistentMultipleTabManager()})});auth=getAuth(app);await setPersistence(auth,browserLocalPersistence);signOutButton.addEventListener('click',()=>signOut(auth));onAuthStateChanged(auth,u=>u?signedIn(u):signedOut());addEventListener('online',networkStatus);addEventListener('offline',networkStatus)}catch(e){configurationView.hidden=false;configurationView.innerHTML=`<h2>Firebase initialization failed</h2><p>${friendly(e)}</p>`;console.error(e)}}
serviceWorker();init();


const form=document.querySelector('#weight-form'),weightInput=document.querySelector('#weight'),dateInput=document.querySelector('#date'),formMessage=document.querySelector('#form-message'),list=document.querySelector('#weight-list'),empty=document.querySelector('#empty'),count=document.querySelector('#entry-count');
function render(entries){list.replaceChildren();empty.hidden=entries.length>0;count.textContent=`${entries.length} ${entries.length===1?'entry':'entries'}`;for(const e of entries){const li=document.createElement('li');li.className='item';const d=document.createElement('span');d.className='date';d.textContent=formatDate(e.date);const group=document.createElement('div');group.style.textAlign='right';const v=document.createElement('div');v.className='value';v.textContent=`${Number(e.weight).toFixed(1)} kg`;group.append(v);if(e.pending){const p=document.createElement('span');p.className='pending';p.textContent='Waiting to sync';group.append(p)}li.append(d,group);list.append(li)}}
function subscribeToWeights(uid){unsubscribeWeights?.();unsubscribeWeights=onSnapshot(query(weights(uid),orderBy('date','desc')),{includeMetadataChanges:true},snap=>{latestSnapshotFromCache=snap.metadata.fromCache;hasPendingWrites=snap.metadata.hasPendingWrites;render(snap.docs.map(d=>({id:d.id,...d.data(),pending:d.metadata.hasPendingWrites})));networkStatus()},e=>msg(formMessage,friendly(e),true))}
form.addEventListener('submit',e=>{e.preventDefault();msg(formMessage,'');if(!activeUser){msg(formMessage,'Sign in before saving.',true);return}const weight=Number(weightInput.value),date=dateInput.value;if(!Number.isFinite(weight)||weight<20||weight>500||!date){msg(formMessage,'Enter a valid date and a weight between 20 and 500 kg.',true);return}setDoc(doc(weights(activeUser.uid),date),{date,weight,updatedAt:serverTimestamp()}).catch(e=>msg(formMessage,friendly(e),true));weightInput.value='';msg(formMessage,navigator.onLine?'Saved locally and queued for Firebase synchronization.':'Saved locally. It will synchronize when online.');weightInput.focus()});dateInput.value=today();
